/** Test block generated by Gadwick */
describe('UpdatingFeatures', function() {
	it('Updating feature name & description', function() {
		cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell');
		cy.get(`.article-title`).should(`have.text`, "Why Cypress?");
	})
})