/** Test block generated by Gadwick */
describe('Updating Features', function() {
	it('Updating feature name & description', function() {
		// Test steps here. See the gadwick site for examples.
		
		cy.visit('localhost:3000');
		cy.get(".login").click();
		cy.get(".sidebar_features").click();
		const name = cy.get("feature_entry_updating_features_name").invoke("text");
		const nameCell = cy.get("feature_entry_updating_features_name");
		nameCell.click();
		nameCell.get("input").type("New Name");
		nameCell.click();
		// .should('match', "Updating Features");
	})
})