/** Test block generated by Gadwick */
describe('UpdatingFeatures', function() {
	it('Updating feature name & description', function() {
		// Test steps here. See the gadwick site for examples.
		console.log(`Starting test`);
		cy.visit('localhost:3006');
		cy.get("#login").click();
		cy.get("#sidebar_features").click();
		console.log(`Ending test`);
		// const name = cy.get("feature_entry_updating_features_name").invoke("text");
		// const nameCell = cy.get("feature_entry_updating_features_name");
		// nameCell.click();
		// nameCell.get("input").type("New Name");
		// nameCell.click();
		// .should('match', "Updating Features");
	})
})