/** Test block generated by Gadwick */
describe(`App management on website`, function() {
	it(`I can create, update and delete apps via the website`, function() {
		// Write your test behaviour here.
	})
})