const axios = require('axios');

const endpoint = `http://localhost:3003`;
/** Test block generated by Gadwick */
describe(`Feature API`, function() {
	it(`CRUD for features`, async function() {
        // C
        const featureArray = await axios.post(`${endpoint}/features`, { name: "test feature", description: "A testing feature", app_id: "0" })// TODO: stats#
        const feature = featureArray.data;
        // console.dir(feature)
        // R
        let features = (await axios.get(`${endpoint}/features/?id=${feature.id}`)).data[0];
        // console.dir(features);
        expect(features.id).toBe(feature.id); // TODO: Deep equal
        // // U

        // // D
        await axios.delete(`${endpoint}/features/${feature.id}`);
        try
        {
            await axios.get(`${endpoint}/features/?id=${feature.id}`);
        }
        catch (err)
        {
            expect(err.response.status).toBe(404);
            return;
        }
        fail(`Endpoint did not return 404 for deleted feature`)
	})
})