/** Test block generated by Gadwick */
describe('NPM Module Config', function() {
	it('I can update and configure a gadwick app from the npm cli', function() {
		// Test steps here. See the gadwick site for examples.
	})
})