const axios = require('axios');

const endpoint = `http://localhost:3003`;
/** Test block generated by Gadwick */
describe(`Tags API`, function() {
	it(`CRUD for tags`, async function() {
        // C
        const featureArray = await axios.post(`${endpoint}/tags`, { name: "test tag", app_id: "0" })
        const feature = featureArray.data;
        // console.dir(feature)
        // R
        let tag = (await axios.get(`${endpoint}/tags/${feature.id}`)).data;
        console.dir(tag);
        expect(tag.id).toBe(feature.id); // TODO: Deep equal
        // app
        let tags = (await axios.get(`${endpoint}/tags/app/0`)).data;
        // console.dir(features);
        expect(tags.length).toBe(1);

        // // D
        let singleGetResponse;
        await axios.delete(`${endpoint}/tags/${tag.id}`);
        try
        {
            singleGetResponse = await axios.get(`${endpoint}/tags/${tag.id}`);
        }
        catch (err)
        {
            expect(err.response.status).toBe(404, "Specific tag did not return 404 after being deleted.");
            return;
        }
        expect(singleGetResponse.status).toBe(404, "Specific tag did not return 404 after being deleted.");
        let collectionGetResponse = await axios.get(`${endpoint}/tags/app/0`);
        expect(collectionGetResponse.data.length).toBe(0);
	})
})